/***************************************************************************
 *  Copyright (C) 2010  Philipp Nordhus                                    *
 *                                                                         *
 *  This program is free software: you can redistribute it and/or modify   *
 *  it under the terms of the GNU General Public License as published by   *
 *  the Free Software Foundation, either version 3 of the License, or      *
 *  (at your option) any later version.                                    *
 *                                                                         *
 *  This program is distributed in the hope that it will be useful,        *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *  GNU General Public License for more details.                           *
 *                                                                         *
 *  You should have received a copy of the GNU General Public License      *
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.  *
 ***************************************************************************/

#ifndef TXT_STRINGTABLE_H
#define TXT_STRINGTABLE_H


#include <QStringList>


namespace txt {


enum String
{
    Text0,
    Text1,
    Text2,
    MainMenu_NewGame,
    MainMenu_QuitGame,
    Notebook_Sound,
    Notebook_Graphics,
    Notebook_Movies,
    Text8,
    Text9,
    Text10,
    Text11,
    Text12,
    Text13,
    Notebook_Title,
    Notebook_TitleLine,
    Notebook_Missions,
    Notebook_LoadSave,
    Notebook_Map,
    Notebook_Options,
    Notebook_Back,
    Notebook_Missions_Title,
    Notebook_Missions_TitleLine,
    Text23,
    Text24,
    Text25,
    Text26,
    Text27,
    Text28,
    Text29,
    Text30,
    Text31,
    Text32,
    EnCom_Via,
    EnCom_Person,
    Text35,
    Text36,
    Text37,
    Text38,
    Text39,
    Text40,
    Text41,
    Text42,
    Text43,
    Text44,
    Text45,
    Text46,
    Text47,
    Text48,
    Text49,
    Text50,
    Text51,
    Text52,
    Text53,
    Text54,
    Notebook_Options_Title,
    Notebook_Options_TitleLine,
    Notebook_InputDevices,
    Text58,
    Text59,
    Text60,
    Text61,
    Text62,
    Text63,
    Text64,
    Text65,
    Text66,
    Text67,
    Text68,
    Text69,
    Text70,
    Text71,
    Notebook_Movies_Title,
    Notebook_Movies_TitleLine,
    Notebook_Movies_Autopilot_Yes,
    Notebook_Movies_Autopilot_No,
    Notebook_Movies_Approach_Yes,
    Notebook_Movies_Approach_No,
    Text78,
    Text79,
    Text80,
    Text81,
    Text82,
    Text83,
    Text84,
    Text85,
    Text86,
    Text87,
    Text88,
    Text89,
    Text90,
    Text91,
    Text92,
    Text93,
    Text94,
    Text95,
    Notebook_Movies_Harbour_Yes,
    Notebook_Movies_Harbour_No,
    DialogTitle,
    Text99,
    Text100,
    Notebook_QuitGame,
    Text102,
    Text103,
    Text104,
    Text105,
    Text106,
    Text107,
    Text108,
    Text109,
    MainMenu_Load,
    MainMenu_Credits,
    MainMenu_Training,
    Text113,
    Text114,
    Text115,
    Text116,
    Text117,
    MainMenu,
    Text119,
    Text120,
    Text121,
    Text122,
    Text123,
    Text124,
    Text125,
    Text126,
    Text127,
    Text128,
    Text129,
    Text130,
    Text131,
    Text132,
    Text133,
    Text134,
    Text135,
    Text136,
    Text137,
    Text138,
    Text139,
    Departure_Abort,
    Departure_Title,
    DialogEnd,
    Notebook_MoviePlayer,
    Notebook_MoviePlayer_Title,
    Notebook_MoviePlayer_TitleLine,
    Text146,
    FirstMovie,
    Text148,
    Text149,
    Text150,
    Text151,
    Text152,
    Text153,
    Text154,
    Text155,
    Text156,
    Text157,
    Text158,
    Text159,
    Text160,
    Text161,
    Text162,
    Text163,
    Text164,
    Text165,
    Text166,
    Text167,
    Text168,
    Text169,
    Text170,
    Text171,
    Text172,
    Text173,
    Text174,
    Text175,
    Text176,
    Text177,
    Text178,
    Text179,
    Text180,
    Text181,
    Text182,
    Text183,
    Text184,
    Text185,
    Text186,
    Text187,
    Text188,
    Text189,
    Text190,
};

enum StringFight
{
    Briefing_Targets,
    Briefing_TargetsLine,
    Briefing_Hints,
    Briefing_HintsLine,
    Briefing_PressAnyKey,
    Fight5,
    Fight6,
    Fight7,
    Fight8,
    Fight9,
    Fight10,
    Fight11,
    Fight12,
    Fight13,
    Fight14,
    Fight15,
    Fight16,
    Fight17,
    Fight18,
    Fight19,
    Fight20,
    Fight21,
    Fight22,
    Fight23,
    Fight24,
    Fight25,
    Fight26,
    Fight27,
    Fight28,
    Fight29,
    Fight30,
    Fight31,
    Fight32,
    Fight33,
    Fight34,
    Fight35,
    Fight36,
    Fight37,
    Fight38,
    Fight39,
    Fight40,
    Fight41,
    Fight42,
    Fight43,
    Fight44,
    Fight45,
    Fight46,
    Fight47,
    Fight48,
    Fight49,
    Fight50,
    Fight51,
    Fight52,
    Fight53,
    Fight54,
    Fight55,
    Fight56,
    Fight57,
    Fight58,
    Fight59,
    Fight60,
    Fight61,
    Fight62,
    Fight63,
    Fight64,
    Fight65,
    Fight66,
    Fight67,
    Fight68,
    Fight69,
    Fight70,
    Fight71,
    Fight72,
    Fight73,
    Fight74,
    Fight75,
    Fight76,
    Fight77,
    Fight78,
    Fight79,
    Fight80,
    Fight81,
    Fight82,
    Fight83,
    Fight84,
    Fight85,
    Fight86,
    Fight87,
    Fight88,
    Fight89,
};


class StringTable
{
public:
    static bool load();
    static QString get(String string);
    static QString get(StringFight string);

private:
    static QStringList m_tableDesktop;
    static QStringList m_tableFight;
};


} // namespace txt


#endif // TXT_STRINGTABLE_H
